### PR TITLE
Call to undefined method Magento\Bundle\Model\Product\Type::getConfigurableAttributeCollection() is Fixed as per code

### PR DESCRIPTION
**Pull request by kanhaiya5590**
https://github.com/magento/magento2/issues/21663#issuecomment-674535792

We have install facebook-for-magento2 from market place and we see the issue in checkout 

As we seen code in https://github.com/facebookincubator/facebook-for-magento2/tree/master Master branch, which will solve most of the issue.

Please do merge the PR into market place branch and move the changes to https://marketplace.magento.com/facebook-facebook-for-magento2.html so all the other users can get proper banifit from extension

### CODE REVIEW

**Comment by kanhaiya5590** [comment]
contributors to sign our Contributor License Agreement - **Done**

**Comment by kanhaiya5590** [comment]
I think this is the right to release updated version of FB extension, as many others getting issue in there application - @facebook-github-bot

**Comment by ecreatestudio** [comment]
Hi, we have found a similar issue in checkout for a simple product calling method: Magento\Catalog\Model\Product\Type\Simple::getConfigurableAttributeCollection()

This only occurs when adding a simple product first that is not associated with a Configurable Product, and then adding a simple product to cart that is associated with a configurable product.

The stack trace is below. Do you think your fix for bundle products will also apply to this similar issue with Simple products?

[2021-05-18 23:51:32] main.CRITICAL: Error: Call to undefined method Magento\Catalog\Model\Product\Type\Simple::getConfigurableAttributeCollection() in /home/web/deployment/flag/releases/8/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52

Stack trace:

#0 /home/web/deployment/flag/releases/8/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\ConfigurableProduct\Helper\Product\Options\Loader->load(Object(Magento\Catalog\Model\Product\Interceptor))

#1 /home/web/deployment/flag/releases/8/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\ConfigurableProduct\Model\Product\ReadHandler->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)

#2 /home/web/deployment/flag/releases/8/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\Framework\EntityManager\Operation\Read\ReadExtensions->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)

#3 /home/web/deployment/flag/releases/8/vendor/magento/framework/EntityManager/EntityManager.php(70): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Product\Interceptor), '115', Array)

#4 /home/web/deployment/flag/releases/8/vendor/magento/module-catalog/Model/ResourceModel/Product.php(722): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Product\Interceptor), '115')

#5 /home/web/deployment/flag/releases/8/vendor/magento/framework/Model/AbstractModel.php(540): Magento\Catalog\Model\ResourceModel\Product->load(Object(Magento\Catalog\Model\Product\Interceptor), '115', NULL)

#6 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Model\AbstractModel->load('115')

#7 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\Product\Interceptor->___callParent('load', Array)

#8 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Product\Interceptor->Magento\Framework\Interception\{closure}('115')

#9 /home/web/deployment/flag/releases/8/generated/code/Magento/Catalog/Model/Product/Interceptor.php(50): Magento\Catalog\Model\Product\Interceptor->___callPlugins('load', Array, Array)

#10 /home/web/deployment/flag/releases/8/vendor/facebook/facebook-for-magento2/Helper/MagentoDataHelper.php(189): Magento\Catalog\Model\Product\Interceptor->load('115')

#11 /home/web/deployment/flag/releases/8/vendor/facebook/facebook-for-magento2/Observer/InitiateCheckout.php(64): Facebook\BusinessExtension\Helper\MagentoDataHelper->getCartContentIds()

#12 /home/web/deployment/flag/releases/8/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Facebook\BusinessExtension\Observer\InitiateCheckout->execute(Object(Magento\Framework\Event\Observer))

#13 /home/web/deployment/flag/releases/8/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Facebook\BusinessExtension\Observer\InitiateCheckout), Object(Magento\Framework\Event\Observer))

#14 /home/web/deployment/flag/releases/8/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))

#15 /home/web/deployment/flag/releases/8/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('facebook_busine...', Array)

#16 /home/web/deployment/flag/releases/8/vendor/facebook/facebook-for-magento2/Block/Pixel/Common.php(152): Magento\Framework\Event\Manager\Proxy->dispatch('facebook_busine...', Array)

#17 /home/web/deployment/flag/releases/8/vendor/facebook/facebook-for-magento2/view/frontend/templates/pixel/initiate_checkout.phtml(5): Facebook\BusinessExtension\Block\Pixel\Common->trackServerEvent('f2b0443b-bc4b-4...')

#18 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/web/deplo...')

#19 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Facebook\BusinessExtension\Block\Pixel\InitiateCheckout), '/home/web/deplo...', Array)

#20 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)

#21 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Facebook\BusinessExtension\Block\Pixel\InitiateCheckout), '/home/web/deplo...', Array)

#22 /home/web/deployment/flag/releases/8/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)

#23 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Facebook\BusinessExtension\Block\Pixel\InitiateCheckout), '/home/web/deplo...', Array)

#24 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/home/web/deplo...')

#25 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml()

#26 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()

#27 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()

#28 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()

#29 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('fbe.pixel.inita...')

#30 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('fbe.pixel.inita...')

#31 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('fbe.pixel.inita...', false)

#32 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('before.body.end', false)

#33 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end')

#34 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('before.body.end', false)

#35 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)

#36 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')

#37 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)

#38 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)

#39 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')

#40 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')

#41 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()

#42 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)

#43 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()

#44 /home/web/deployment/flag/releases/8/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)

#45 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()

#46 /home/web/deployment/flag/releases/8/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))

#47 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))

#48 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)

#49 /home/web/deployment/flag/releases/8/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))

#50 /home/web/deployment/flag/releases/8/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)

#51 /home/web/deployment/flag/releases/8/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))

#52 /home/web/deployment/flag/releases/8/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()

#53 /home/web/deployment/flag/releases/8/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

#54 {main} [] []

**Comment by zlik** [comment]
@kanhaiya5590, thank you for preparing a pull request. Looks like you've used the `marketplace` branch. This branch is actually out of date and is not used. Can you please prepare a new pull request using `master`? Thanks!

**Comment by kanhaiya5590** [comment]
Hi @zlik ,

As i seen https://marketplace.magento.com/facebook-facebook-for-magento2.html last update done on 21 April, 2021

So thought that in github https://github.com/facebookincubator/facebook-for-magento2/tree/marketplace branch and magento market place code in SYNC.

we are facing issue with Magento market place code so thought rising this PR will update Github https://github.com/facebookincubator/facebook-for-magento2/tree/marketplace as well as Magento Market Place https://marketplace.magento.com/facebook-facebook-for-magento2.html

Hope i share my thought, if we can't merge the Github Master branch code to Magento market place FB extension, no issue we can close this PR. Because the code there in Magento Market place same issue which i mention in main comment.

**Comment by zlik** [comment]
@kanhaiya5590, `marketplace` branch is not in sync. We should probably remove it. Can you please create a pull request against `master`? Once submitted and merged into `master` we can then update the extension code on Magento Marketplace. Thanks!

**Pull request closed without merging**
